include "vale.i.dfy"
include "printer.s.dfy"
include "../../../gen/impl/otbn/falcon/ot_falcon.i.dfy"

module modexp_printer {
  
import opened ot_machine
import opened ot_falcon
import opened otbn_printer

method Main()
{
    var p := new Printer({"ot_falcon"});
    var comment := "/*\n  This code is generated by the ***** project: https://*****\n*/\n";
    print(comment);

    reveal va_code_ot_falcon();
    var c := va_code_ot_falcon();
    p.printTopLevelProc(c);
}

}
